# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-example',
                'doc_host': 'https://s.github.io',
                'git_url': 'https://github.com/s/nbdev-example',
                'lib_path': 'nbdev_example/nested'},
  'syms': {'nested.core': {'nested.core.foo': ('core.html#foo', 'nested/core.py')}}}
